export enum AccessoriesEnum {
  NONE = "none",
  ACE_OF_HEARTS = "aceOfHearts",
  CHARIZARD_BALLOON = "charizardBalloon",
  ELEGANT = "elegant",
  BOXING_GLOVES = "boxingGloves",
  MASTER_BALL = "masterBall",
  CHRISTMAS = "christmas",
  MEW = "mew",
  PARTY = "party",
  SKULL = "skull",
  BLUE_VANS = "blueVans",
  RED_VANS = "redVans",
  CIGARETTE = "cigarrette",
  HOT = "hot",
  DIAMOND = "diamond",
  SHARINGAN = "sharingan",
  LIGHT = "light",
  DARK = "dark",
}
