import { PokemonController } from "./controller/PokemonController";
import { PokemonTypesController } from "./controller/PokemonTypesController";
import { TeamController } from "./controller/TeamController";
import { BoxController } from "./controller/BoxController";
import { UserController } from "./controller/UserController";
import authenticateJWT from "./middleware/auth";
import { TrainerPokemonController } from "./controller/TrainerPokemonController";
import { GameLevelController } from "./controller/GameLevelController";
import { AccessoryController } from "./controller/AccessoryController";

export const Routes = [
  {
    method: "get",
    route: "/pokemon",
    controller: PokemonController,
    action: "all",
  },
  {
    method: "post",
    route: "/pokemon/all",
    controller: PokemonController,
    action: "saveAll",
  },
  {
    method: "get",
    route: "/pokemon/:id",
    controller: PokemonController,
    action: "one",
  },
  {
    method: "get",
    route: "/pokemon/pokeballProbs/:pokeballType",
    controller: PokemonController,
    action: "pokeballProbs",
  },
  {
    method: "post",
    route: "/pokemon",
    controller: PokemonController,
    action: "save",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/pokemon/:id",
    controller: PokemonController,
    action: "remove",
    middleware: [authenticateJWT],
  },
  {
    method: "patch",
    route: "/trainerPokemon/:id",
    controller: TrainerPokemonController,
    action: "update",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/dragPokemonInBox",
    controller: TrainerPokemonController,
    action: "dragPokemonInBox",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/dragPokemonInTeam",
    controller: TrainerPokemonController,
    action: "dragPokemonInTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/movePokemonFromTeamToBox",
    controller: TrainerPokemonController,
    action: "movePokemonFromTeamToBox",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/movePokemonFromBoxToTeam",
    controller: TrainerPokemonController,
    action: "movePokemonFromBoxToTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/getMergeResults",
    controller: TrainerPokemonController,
    action: "getMergeResults",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/trainerPokemon/merge",
    controller: TrainerPokemonController,
    action: "merge",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/login",
    controller: UserController,
    action: "login",
  },
  {
    method: "get",
    route: "/user",
    controller: UserController,
    action: "all",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/allPokemons",
    controller: UserController,
    action: "allPokemons",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/pokedex",
    controller: UserController,
    action: "pokedex",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/allTeams",
    controller: UserController,
    action: "allTeams",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/allBoxes",
    controller: UserController,
    action: "allBoxes",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/allPokemonLaboratory",
    controller: UserController,
    action: "allPokemonLaboratory",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/gameLevel/:levelId",
    controller: UserController,
    action: "getUserGameLevel",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/allGameLevels",
    controller: UserController,
    action: "allGameLevels",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getById/:id",
    controller: UserController,
    action: "one",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user",
    controller: UserController,
    action: "register",
  },
  {
    method: "post",
    route: "/user/saveAvatar",
    controller: UserController,
    action: "saveAvatar",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getAvatarOptions",
    controller: UserController,
    action: "getAvatarOptions",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getAccessories",
    controller: UserController,
    action: "getUserUnlockedAccessories",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getLeagueTeam",
    controller: UserController,
    action: "getLeagueTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getLeagueLevels",
    controller: UserController,
    action: "getLeagueLevels",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getLeagueLevel/:levelId",
    controller: UserController,
    action: "getLeagueLevel",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/createLeagueTeam",
    controller: UserController,
    action: "createLeagueTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/addPokemonToUser",
    controller: UserController,
    action: "addPokemonToUser",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/assignPokemonToFirstTeam",
    controller: UserController,
    action: "assignPokemonToFirstTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/sendPokemonToFirstBox",
    controller: UserController,
    action: "sendPokemonToFirstBox",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/switchBoxForTeamPokemon",
    controller: UserController,
    action: "switchBoxForTeamPokemon",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/openPokeball",
    controller: UserController,
    action: "openPokeball",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/user/redeemCode",
    controller: UserController,
    action: "redeemCode",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/user/removePokemonFromUser",
    controller: UserController,
    action: "removePokemonFromUser",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/isUserTeamAbleToPlayLevel",
    controller: UserController,
    action: "isUserTeamAbleToPlayLevel",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/user/getUserStats",
    controller: UserController,
    action: "getUserStats",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/user/:id",
    controller: UserController,
    action: "remove",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/pokemonTypes",
    controller: PokemonTypesController,
    action: "all",
  },
  {
    method: "get",
    route: "/pokemonTypes/:id",
    controller: PokemonTypesController,
    action: "one",
  },
  {
    method: "post",
    route: "/pokemonTypes",
    controller: PokemonTypesController,
    action: "save",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/pokemonTypes/all",
    controller: PokemonTypesController,
    action: "saveAll",
  },
  {
    method: "delete",
    route: "/pokemonTypes/:id",
    controller: PokemonTypesController,
    action: "remove",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/team",
    controller: TeamController,
    action: "all",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/team/:id",
    controller: TeamController,
    action: "one",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/team",
    controller: TeamController,
    action: "save",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/team/addPokemon",
    controller: TeamController,
    action: "addPokemonToTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/team/removePokemon",
    controller: TeamController,
    action: "removePokemonFromTeam",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/team/:id",
    controller: TeamController,
    action: "remove",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/box",
    controller: BoxController,
    action: "all",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/box/:id",
    controller: BoxController,
    action: "one",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/box",
    controller: BoxController,
    action: "save",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/box/addPokemon",
    controller: BoxController,
    action: "addPokemonToBox",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/box/removePokemon",
    controller: BoxController,
    action: "removePokemonFromBox",
    middleware: [authenticateJWT],
  },
  {
    method: "delete",
    route: "/box/:id",
    controller: BoxController,
    action: "remove",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/gameLevel/updateGameLevelState",
    controller: GameLevelController,
    action: "updateGameLevelStatus",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/gameLevel/claimGameLevelReward",
    controller: GameLevelController,
    action: "claimGameLevelReward",
    middleware: [authenticateJWT],
  },
  {
    method: "post",
    route: "/gameLevel/unlockNextGameLevel",
    controller: GameLevelController,
    action: "unlockNextGameLevel",
    middleware: [authenticateJWT],
  },
  {
    method: "get",
    route: "/accessory/getAccessory/:code",
    controller: AccessoryController,
    action: "getAccessoryByCode",
  },
];
