export type TypeMap = {
  [key: number]: string[];
};

export const TYPE_MAP: TypeMap = {
  1: [
    "Golpe Cuerpo",
    "Doble Filo",
    "Placaje",
    "Cabezazo Zen",
    "Corte",
    "Gigaimpacto",
    "Derribo",
    "Rápido",
    "Desenrollar",
    "Latigazo",
  ],
  2: [
    "Puño Dinámico",
    "Puño Fuego",
    "Puño Trueno",
    "Golpe Karate",
    "A Bocajarro",
    "Patada Baja",
    "Patada Salto",
    "Puño Certero",
    "Onda Vacío",
    "Metrónomo",
  ],
  3: [
    "Vendaval",
    "Pájaro Osado",
    "Ala de Acero",
    "Tajo Aéreo",
    "Ataque Ala",
    "Chupavidas",
    "Golpe Aéreo",
    "Pico Taladro",
    "Danza Aérea",
    "Acróbata",
  ],
  4: [
    "Bomba Lodo",
    "Lanzamugre",
    "Puya Nociva",
    "Colmillo Veneno",
    "Lodo Gélido",
    "Aguijón Letal",
    "Púas Tóxicas",
    "Lanza Mugre",
    "Onda Tóxica",
    "Garra Umbría",
  ],
  5: [
    "Terremoto",
    "Bofetón Lodo",
    "Tierra Viva",
    "Avalancha",
    "Fuerza Telúrica",
    "Excavar",
    "Disparo Lodo",
    "Magnitud",
    "Pulso Tierra",
    "Barrera Arena",
  ],
  6: [
    "Avalancha",
    "Roca Afilada",
    "Tumba Rocas",
    "Desenrollar",
    "Roca Veloz",
    "Pedrada",
    "Poder Pasado",
    "Poder Rocoso",
    "Trampa Rocas",
    "Lanzarrocas",
  ],
  7: [
    "Chupavidas",
    "Megacuerno",
    "Tijera X",
    "Picadura",
    "Cornada",
    "Golpe Mordaza",
    "Zumbido",
    "Ida y Vuelta",
    "Acoso",
    "Aguijón Letal",
  ],
  8: [
    "Garra Umbría",
    "Bola Sombra",
    "Tinieblas",
    "Alarido",
    "Golpe Fantasma",
    "Puño Sombra",
    "Rayo Umbrío",
    "Sombra Vil",
    "Lengüetazo",
    "Fuerza Fantasma",
  ],
  9: [
    "Cabezahierro",
    "Puño Meteoro",
    "Garra Metal",
    "Ala de Acero",
    "Cañón de Flash",
    "Cola Férrea",
    "Patada de Acero",
    "Bomba Imán",
    "Meteoro Bola",
    "Trampa Acero",
  ],
  10: [
    "Llamarada",
    "Lanzallamas",
    "Giro Fuego",
    "Ascuas",
    "Colmillo Ígneo",
    "Sofoco",
    "Nitrocarga",
    "Giro Fuego",
    "Envite Ígneo",
    "Pirotecnia",
  ],
  11: [
    "Surf",
    "Hidrobomba",
    "Burbuja",
    "Chorro de Agua",
    "Aqua Jet",
    "Pistola Agua",
    "Aqua Cola",
    "Cascada",
    "Hidropulso",
    "Escaldar",
  ],
  12: [
    "Hoja Afilada",
    "Latigazo",
    "Danza Pétalo",
    "Energibola",
    "Rayo Solar",
    "Corte Furia",
    "Látigo Cepa",
    "Hierba Lazo",
    "Follaje",
    "Gigadrenado",
  ],
  13: [
    "Rayo",
    "Impactrueno",
    "Chispazo",
    "Trueno",
    "Electrocañón",
    "Cola Férrea",
    "Electropulso",
    "Puño Trueno",
    "Voltio Cruel",
    "Chispa",
  ],
  14: [
    "Psíquico",
    "Confusión",
    "Onda Mental",
    "Premonición",
    "Psicocarga",
    "Psicoonda",
    "Psico Corte",
    "Hiperrayo",
    "Cabezazo Zen",
    "Fuerza Lunar",
  ],
  15: [
    "Ventisca",
    "Rayo Hielo",
    "Frío Polar",
    "Canto Helado",
    "Nevada",
    "Viento Hielo",
    "Golpe Hielo",
    "Puño Hielo",
    "Alud",
    "Granizo",
  ],
  16: [
    "Enfado",
    "Cometa Draco",
    "Pulso Dragón",
    "Garra Dragón",
    "Cola Dragón",
    "Llamarada",
    "Vuelo",
    "Fuerza Dragón",
    "Dracoaliento",
    "Devastación",
  ],
  17: [
    "Triturar",
    "Pulso Umbrío",
    "Golpe Bajo",
    "Finta",
    "Mordisco",
    "Alarido",
    "Juego Sucio",
    "Garra Umbría",
    "Sombra Vil",
    "Ladrón",
  ],
  18: [
    "Brillo Mágico",
    "Vozarrón",
    "Fuerza Lunar",
    "Carantoña",
    "Aromaterapia",
    "Cañón Floral",
    "Viento Feérico",
    "Campo de Niebla",
    "Rayo Espejismo",
    "Deslumbrar",
  ],
};
